import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import { FontSizeInitializer } from "@/components/providers/font-size-initializer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html suppressHydrationWarning className="overflow-x-hidden max-w-full">
        <body className="overflow-x-hidden max-w-full">
          {/* Initialize font size from localStorage */}
          <FontSizeInitializer />
          {/* Clerk CAPTCHA element - required for bot protection */}
          <div id="clerk-captcha" style={{ display: "none" }} />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
