import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html suppressHydrationWarning>
        <body>
          {/* Clerk CAPTCHA element - required for bot protection */}
          <div id="clerk-captcha" style={{ display: "none" }} />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
